In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import joblib
# Dataset provided
data = {
    'StudyHours': [1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11],
    'Result': [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
}

df = pd.DataFrame(data)

print("First 5 rows of the dataset:")
display(df.head())

First 5 rows of the dataset:

   StudyHours  Result
0           1       0
1           2       0
2           2       0
3           3       0
4           3       0

In [24]:
X = df[['StudyHours']]
y = df['Result']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training data shape: {X_train.shape}")
print(f"Testing data shape: {X_test.shape}")

Training data shape: (16, 1)
Testing data shape: (4, 1)

In [25]:
model = LogisticRegression()

model.fit(X_train, y_train)

print("Model training complete.")

Model training complete.

In [26]:
# print(f"Model Intercept: {model.intercept_[0]:.4f}")

# print(f"Model Coefficients (StudyHours, Attendance): {model.coef_[0][0]:.4f}, {model.coef_[0][1]:.4f}")

In [27]:
y_pred=model.predict(X_test)
pred_df=pd.DataFrame({'Actual':y_test,'Predicted':y_pred})
display(pred_df)

    Actual  Predicted
0        0          0
17       1          1
15       1          1
1        0          0

In [28]:
accuracy_score(y_pred,y_test)

1.0

In [29]:
confusion_matrix(y_test, y_pred)

array([[2, 0],
       [0, 2]])

In [30]:
new_data={
    'StudyHours': [6,2],
}
new_df=pd.DataFrame(new_data)

new_pred=model.predict(new_df)
new_df['Result']=new_pred
display(new_df)

   StudyHours  Result
0           6       1
1           2       0

In [31]:
joblib.dump(model, "student_pass_fail_model.pkl")
print("Model saved successfully!")

Model saved successfully!